### PR TITLE
Notification Page

### PR DESCRIPTION
**Pull request by ahmedelsayad11**
closing #401 

1- created the notification page

2- created the notification loader component

### CODE REVIEW

**Comment by AhmedAdel999** [comment]
- Rename the path from `notification` to `notifications`.
- Make the notifications icon in `Navigation` redirect to `/notifications`.

**Review by AhmedAdel999 — CHANGES_REQUESTED** [review]
- Rename the path from notification to notifications.
 - Make the notifications icon in Navigation redirect to /notifications.

**Review by omarawad0 — APPROVED** [review]
LGTM

**Review by AhmedAdel999 — APPROVED** [review]
LGTM

**Pull request merged**
