### PR TITLE
Slider component

### PR DESCRIPTION
**Pull request by AhmedAdel999**
- Fixed some issues related to circular slider.
- Added css module file.
- Added new snapshot files.

### CODE REVIEW

**Review by Tramsi — CHANGES_REQUESTED** [review]
1) There are a couple of bugs I faced during using the component in circular type:
- progress reflected on the circle isn't the right progress
- at progress 50 colors change to dark
Screenshot from 2021-05-29 22-01-58

2) the default height for the vertical slider is a fixed "300px",  it should be responsive and have the full height of its container and give the user the ability to add custom height if needed,

also, the prop "height" name isn't descriptive enough for what it does, it indicates that it can change the height of component at any type despite it only affects the vertical slider type.

3) consider adding transition for the changing animation, this would give a fluid transition while progress changing.

4) consider adding more comments in your component

**Comment by AhmedAdel999** [comment]
Almost all of the requested changes have been added except for:
- I have changed nothing about circular progress as it looks perfectly fine to me.
- Didn't add the transition property as there are some errors thrown at me when I try to modify tailwind to make it work with height transition(I shall open an issue with it soon).

**Comment by Tramsi** [comment]
@AhmedAdel999 
- you can use a transition-all class that would work fine for all three types of progress bar and you don't have a lot of changes to worry about the "all", just color and width or height so it will work as it should

**Review by Tramsi — APPROVED** [review]
LGTM

**Pull request merged**
